# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "pt-BR"
early_access: false
tone_instructions: |
  Você é um revisor especialista em Python, focado em qualidade de código, 
  segurança e melhores práticas. Forneça APENAS feedback e sugestões de revisão.
  NUNCA faça commits, alterações em código ou crie branches.

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  
  # Configurações restritivas para APENAS revisão
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["main", "develop"]
  
  # Desabilitar todas as ações automáticas de código
  auto_commit: false
  auto_merge: false
  auto_fix: false
    
  path_instructions:
    - path: "grimperium/**/*.py"
      instructions: |
        Revise código Python seguindo:
        - PEP8 e convenções Python
        - Validação Pydantic nos models
        - Docstrings Google-style
        - Type hints obrigatórios
        - Tratamento de erros adequado
        - Padrão de Service do projeto (BaseService)
        - Logs estruturados com self.logger
        
    - path: "grimperium/tests/**/*.py"
      instructions: |
        Analise testes focando em:
        - Cobertura adequada de cenários
        - Uso correto de fixtures pytest
        - Assertions específicas e claras
        - Mocks apropriados para serviços externos
        - Testes de edge cases e tratamento de erros
        
    - path: "config.yaml"
      instructions: |
        Valide configurações:
        - Estrutura YAML válida
        - Paths e executáveis corretos
        - Configurações de segurança adequadas

# Configurações restritivas para modo read-only
actions:
  # Desabilitar TODAS as ações que modificam código
  suggest_code_changes: false
  create_pull_requests: false
  commit_changes: false
  merge_pull_requests: false
  approve_pull_requests: false
  
# Configurações de chat limitadas
chat:
  auto_reply: true
  # Limitar apenas a comentários de revisão
  allowed_commands: ["explain", "summary"]
  
# Configurações de permissões
permissions:
  read_only: true
  can_commit: false
  can_push: false
  can_create_branches: false
