# CodeRabbit Configuration - STRICT READ-ONLY MODE
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "pt-BR"
early_access: false

# INSTRUÇÕES EXPLÍCITAS PARA MODO SOMENTE LEITURA
tone_instructions: |
  Você é um revisor de código especialista em Python configurado em MODO SOMENTE LEITURA.
  
  RESPONSABILIDADES:
  ✅ PERMITIDO: Análise de código, comentários de revisão, feedback textual
  ❌ PROIBIDO: Commits, push, criação de branches, alterações de código, pull requests
  
  Forneça APENAS análise e sugestões em português brasileiro.

# CONFIGURAÇÕES DE REVISÃO RESTRITIVAS
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  review_status: false
  collapse_walkthrough: true
  
  # Auto-review habilitado APENAS para comentários
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["main", "develop"]
  
  # DESABILITAR TODAS AS AÇÕES DE MODIFICAÇÃO
  auto_title_update: false
  auto_merge: false
  
  # Instruções específicas por path
  path_instructions:
    - path: "grimperium/**/*.py"
      instructions: |
        Análise focada em:
        - Conformidade PEP8
        - Padrões Pydantic
        - Type hints
        - Docstrings Google-style
        - Arquitetura de Services
        APENAS COMENTÁRIOS - NÃO ALTERE CÓDIGO
        
    - path: "grimperium/tests/**/*.py"
      instructions: |
        Revisar testes para:
        - Cobertura adequada
        - Mocks apropriados
        - Assertions claras
        APENAS ANÁLISE - NÃO MODIFIQUE ARQUIVOS

# DESABILITAR TODAS AS FUNCIONALIDADES DE ESCRITA
knowledge_base:
  learnings:
    enabled: false
  
sequence_diagrams:
  enabled: false

# CONFIGURAÇÕES DE CHAT LIMITADAS
chat:
  auto_reply: false
  
# CONFIGURAÇÕES DE AÇÕES - TODAS DESABILITADAS
actions:
  review: true           # Permitir apenas comentários de revisão
  chat: true            # Permitir apenas chat/perguntas
  describe: false       # Desabilitar geração de descrições
  improve: false        # Desabilitar melhorias automáticas
  auto_incremental: false
  auto_title_update: false

# CONFIGURAÇÕES GLOBAIS RESTRITIVAS
ignore:
  - "**/*.md"
  - "**/*.txt"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/node_modules/**"
  - "**/venv/**"
  - "**/__pycache__/**"