name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Dar permissão de execução ao script
        run: chmod +x setup_environment.sh

      - name: Executar o script de setup do ambiente
        run: ./setup_environment.sh

      - name: Instalar pytest e pytest-cov
        run: pip install pytest pytest-cov

      - name: Rodar testes unitários com cobertura
        run: |
          if [ -d "grimperium/tests" ]; then
            pytest --cov=grimperium --cov-report=xml grimperium/tests
          else
            echo "Sem testes automatizados encontrados."
          fi

      - name: Enviar cobertura para Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
